### ISSUE TITLE
Accounts Dont Work

### ISSUE THREAD

**Issue by CryonicsX** [Ahmeth4n/javatify#1]
Account banning :/

**Comment by Ahmeth4n** [comment]
what do you mean by "banning"? if the passwords of the accounts are changed within 8-10 hours, it means your account is suspicious. but apparently my accounts I created with the same bot still work. can you explain a little more in detail?

**Comment by CryonicsX** [comment]
can u give me contact for talk ? 
my telegram @cryonicx

**Comment by CryonicsX** [comment]
accounts banning when login on spotify bro i'm trying the say this. 
Hesaplar spotify giriş yapıp şarkı dinledikten sonra banlanıyor

**Comment by Ahmeth4n** [comment]
you're probably streaming with selenium. i think there is a problem with your selenium driver. because i tested it with accounts that i just created and created months ago. i didn't have any problems. i suggest you review stream structure

**Comment by CryonicsX** [comment]
no i'm not using selenium. i'm using spotify client

**Comment by CryonicsX** [comment]
bro please give me your contact we can talk on there

**Comment by Ahmeth4n** [comment]
then i have no idea. my accounts are still stable. i'm not continuing to develop this project, sorry.

**Comment by CryonicsX** [comment]
are u using proxies ?
